version: '3.9'

services:
  server:
    build:
      context: ../../
      dockerfile: deploy/build/Dockerfile
      args:
        APP_CONF: config/prod.yml
        APP_RELATIVE_PATH: ./cmd/server
    image: demo-server:v1
    ports:
      - "8081:8080"
    restart: always

  task:
    build:
      context: ../../
      dockerfile: deploy/build/Dockerfile
      args:
        APP_CONF: config/prod.yml
        APP_RELATIVE_PATH: ./cmd/task
    image: demo-task:v1
    restart: always

  # 👇 不常驻
  migration:
    build:
      context: ../../
      dockerfile: deploy/build/Dockerfile
      args:
        APP_CONF: config/prod.yml
        APP_RELATIVE_PATH: ./cmd/migration
    image: demo-migration:v1

